=== bioinformaticsdotca/bioinformaticsdotca.github.io/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "CBW Workshop List Schema",
    "description": "Defines the structure for the workshops.json file.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "url": { "type": "string", "format": "uri-reference" },
            "title": { "type": "string", "minLength": 3 },
            "instructors": {
                "description": "A list of instructor names for the workshop.",
                "type": "array",
                "items": { "type": "string" }
            },
            "tags": { "type": "array", "items": { "type": "string" } },
            "regions": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "string",
                    "enum": ["BC", "Alberta", "Prairies", "Ontario", "Quebec", "Atlantic", "Online"]
                }
            },
            "year": {
                "type": "number",
                "minimum": 1999
            },
            "startDate": { "type": "string", "format": "date" },
            "endDate": { "type": "string", "format": "date" },
            "image": { "type": "string" },
            "locations": {
                "type": "array",
                "minItems": 1,
                "items": { "type": "string" }
            },
            "format": {
                "type": "string",
                "enum": ["Online", "In-person", "Distributed", "Flipped", "Asynchronous"]
            }
        },
        "required": [
            "title", "tags", "regions", "year", "startDate", "endDate", "image", "locations", "format"
        ]
    }
}

=== bioinformaticsdotca/bioinformaticsdotca.github.io/workshops.json
[
{
    "url": "RNA_MonStJ-2606",
    "title": "RNA-seq Analysis",
    "instructors": ["Virginie Calderon","Lourdes Peña-Castillo"],
    "tags": ["RNAseq","bioinformatics","transcriptomics","transcriptome","genomics","NGS","sequencing","expression","pathway","enrichment","DESeq2"],
    "regions": ["Quebec","Atlantic"],
    "year": 2026,
    "startDate": "2026-06-17",
    "endDate": "2026-06-19",
    "image": "img/RNA_icon.png",
    "locations": ["Montréal, QC","St.John's, NL"],
    "format": "Distributed"
},

     {
    "url": "PNA_CalSask-2605",
    "title": "Pathway and Network Analysis",
    "instructors": ["Richard LeDuc","Constance Li","Diogo Pellegrina"],
    "tags": ["Pathways","Network Analysis"],
    "regions": ["Alberta","Prairies"],
    "year": 2026,
    "startDate": "2026-05-12",
    "endDate": "2026-05-13",
    "image": "img/PNA_icon.png",
    "locations": ["Saskatoon, SK","Calgary, AB"],
    "format": "Distributed"
},
  {
    "url": "scRNA_WinTo-2606",
    "title": "Single Cell RNA-seq Analysis",
    "instructors": ["Tallulah Andrews","Chaitra Sarathy","Alyona Ivanova"],
    "tags": [],
    "regions": ["Prairies","Ontario"],
    "year": 2026,
    "startDate": "2026-06-01",
    "endDate": "2026-06-03",
    "image": "img/scRNA_icon.png",
    "locations": ["Winnipeg, MB","Toronto, ON"],
    "format": "Distributed"
},
  {
  "url": "RNA_SaskTo-2606",
  "title": "RNA-seq Analysis",
  "instructors": ["Obi Griffith","Malachi Griffith","Alyona Ivanova","Diogo Pellegrina"],
  "tags": [],
  "regions": ["Prairies","Ontario"],
  "year": 2026,
  "startDate": "2026-06-22",
  "endDate": "2026-06-24",
  "image": "img/RNA_icon.png",
  "locations": ["Saskatoon, SK","Toronto, ON"],
  "format": "Distributed"
},
{
    "url": "RDM_To-2605",
    "title": "Reproducible Research: Essentials for Managing Your Data",
    "instructors": ["Mélanie Courtot","Mitchell Shiell","Linda Xiang","Hardeep Nahal-Bose","Edmund Su","David Bujold"],
    "tags": ["Research Data Management","data discovery","version control","reproducibility","data representation","data model"],
    "regions": ["Ontario"],
    "year": 2026,
    "startDate": "2026-05-27",
    "endDate": "2026-05-27",
    "image": "img/RDM_icon.png",
    "locations": ["Toronto, ON"],
    "format": "In-person"
},
{
    "url": "MLE_EdVan-2604",
    "title": "Machine Learning",
    "instructors": ["David Wishart","Mark Berjanskii","Tanvir Sajed"],
    "tags": ["bioinformatics","machine learning","data science"],
    "regions": ["BC","Alberta"],
    "year": 2026,
    "startDate": "2026-04-22",
    "endDate": "2026-04-23",
    "image": "img/MLE_icon.png",
    "locations": ["Edmonton, AB","Vancouver, BC"],
    "format": "Distributed"
},
    
        {
        "url": "PGE_2025",
        "title": "Pathogen Genomic Epidemiology",
        "instructors": ["Angela McLaughlin","Emma Griffiths","Finlay Maguire","Gary Van Domselaar","Idowu Olawaye","Jennifer Guthrie"],
        "tags": ["Bioinformatics","genomics"],
        "regions": ["Online"],
        "year": 2025,
        "startDate": "2025-11-24",
        "endDate": "2025-11-26",
        "image": "img/PGE_icon.png",
        "locations": ["Online"],
        "format": "Online"
    },

    {
        "url": "MIG_2025",
        "title": "Microbial Genomics",
        "instructors": ["Jared Simpson","Gary van Domselaar","Andrew McArthur","Rob Beiko","Fiona Brinkman"],
        "tags": ["Bioinformatics","genomics"],
        "regions": ["Online"],
        "year": 2025,
        "startDate": "2025-11-20",
        "endDate": "2025-11-22",
        "image": "img/MIG_icon.png",
        "locations": ["Online"],
        "format": "Online"
    },

    {
        "url": "INR_Van-2511",
        "title": "Introduction to R",
        "instructors": ["Rodolfo Lourenzutti","Ido Hatam"],
        "tags": ["R"],
        "regions": ["BC"],
        "year": 2025,
        "startDate": "2025-11-06",
        "endDate": "2025-11-07",
        "image": "img/INR_icon.png",
        "locations": ["Vancouver, BC"],
        "format": "In-person"
    },

    {
        "url": "GPO_Hal-2511",
        "title": "Genomics for Precision Oncology: Halifax, NS",
        "instructors": ["Daniel Gaston","Victor Martinez"],
        "tags": ["Cancer", "Genomics", "Oncology", "AWS", "Halifax", "BHCRI"],
        "regions": ["Atlantic"],
        "year": 2025,
        "startDate": "2025-11-04",
        "endDate": "2025-11-05",
        "image": "img/GPO_icon.png",
        "locations": ["Halifax, NS"],
        "format": "In-person"
    },

    {
        "url": "INR_Ed-2510",
        "title": "Introduction to R",
        "instructors": ["Linglong Kong", "Enze Shi", "Ce Zhang"],
        "tags": ["R", "Bioinformatics", "Statistics"],
        "regions": ["Alberta"],
        "year": 2025,
        "startDate": "2025-10-23",
        "endDate": "2025-10-24",
        "image": "img/INR_icon.png",
        "locations": ["Edmonton AB"],
        "format": "In-person"
    },

    {
        "url": "INR_Mon-2510/",
        "title": "Introduction to R",
        "instructors": ["Celia Greenwood", "Alexandre Reynaud", "W. Alton Russell", "Anna K. Naumova", "Adrien Osakwe", "Han Yu", "Audrey Baguette", "Maximiliane Jousse", "Daniel Gurman", "Rodrigo Migueles Ramirez"
        ],
        "tags": ["Data Science", "R", "Bioinformatics", "Statistics"],
        "regions": ["Quebec", "Online"],
        "year": 2025,
        "startDate": "2025-10-01",
        "endDate": "2025-10-02",
        "image": "img/INR_icon.png",
        "locations": ["Montréal QC", "Online"],
        "format": "Hybrid"
    },

    {
        "url": "INR_Sask-2510/",
        "title": "Introduction to R",
        "instructors": ["Mohamed Helmy"],
        "tags": ["R"],
        "regions": ["Prairies"],
        "year": 2025,
        "startDate": "2025-10-06",
        "endDate": "2025-10-07",
        "image": "img/INR_icon.png",
        "locations": ["Saskatoon, SK"],
        "format": "In-person"
    },

    {
        "url": "GAL_2025/",
        "title": "RNA-seq Analysis Using Galaxy en Français",
        "instructors": ["Virginie Calderon", "Caroline Grou", "Ludovic Malet", "Gaspard Reulet"],
        "tags": ["RNA-seq", "Analysis", "French"],
        "regions": ["Quebec"],
        "year": 2025,
        "startDate": "2025-08-11",
        "endDate": "2025-08-13",
        "image": "img/legacy_icons/l-GAL_icon.png",
        "locations": ["Montreal, QC"],
        "format": "In-person"
    },

    {
        "url": "ISO-V_2025/",
        "title": "Introductory Spatial ’Omics Analysis: Visium HD",
        "instructors": ["Shamini Ayyadhury", "Amina Abow", "Melanie Peralta", "Savannah Kipatrick", "Alyona Ivanova", "Trevor Pugh", "Gary Bader", "Nia Hughes", "Zhibin Lu"],
        "tags": ["Introductory", "Analysis"],
        "regions": ["Ontario", "Online"],
        "year": 2025,
        "startDate": "2025-02-20",
        "endDate": "2025-02-21",
        "image": "img/legacy_icons/l-ISO_icon.jpg",
        "locations": ["Toronto, ON", "Online"],
        "format": "Distributed"
    },

    {
        "url": "AMB_2025/",
        "title": "Advanced Microbiome Analysis",
        "instructors": ["Morgan Langille", "Robyn Wright", "John Parkinson", "Ryan J. McLaughlin", "Juan Santana", "Tony Liu", "Zhibin Lu"],
        "tags": ["Advanced", "Microbiome", "Analysis"],
        "regions": ["BC"],
        "year": 2025,
        "startDate": "2025-05-29",
        "endDate": "2025-05-30",
        "image": "img/legacy_icons/l-AMB_icon.png",
        "locations": ["Vancouver, BC"],
        "format": "In-person"
    },

    {
        "url": "INR_2025/",
        "title": "Introduction to R",
        "instructors": ["Frances Wong"],
        "tags": ["Introductory", "R"],
        "regions": ["Ontario"],
        "year": 2025,
        "startDate": "2025-06-23",
        "endDate": "2025-06-24",
        "image": "img/legacy_icons/l-INR_icon.png",
        "locations": ["Toronto, ON"],
        "format": "In-person"
    },

    {
        "url": "AUR_2025/",
        "title": "Analysis Using R",
        "instructors": ["Shraddha Pai", "Delaram Pouyabahar", "Zoe Klein", "Nia Hughes"],
        "tags": ["Analysis", "R"],
        "regions": ["Ontario"],
        "year": 2025,
        "startDate": "2025-06-25",
        "endDate": "2025-06-26",
        "image": "img/legacy_icons/l-AUR_icon.png",
        "locations": ["Toronto, ON"],
        "format": "In-person"
    },

    {
        "url": "RNA_2025/",
        "title": "RNA-seq Analysis",
        "instructors": ["Malachi Griffith", "Obi Griffith", "Isabel Risch", "Varinder Madhav Verma", "Mobin Khoramjoo", "Nicolas Ho", "Melisa Acun"],
        "tags": ["RNA-seq", "Analysis"],
        "regions": ["Ontario", "Alberta"],
        "year": 2025,
        "startDate": "2025-07-07",
        "endDate": "2025-07-08",
        "image": "img/legacy_icons/l-RNA_icon.png",
        "locations": ["Ottawa, ON", "Edmonton, AB"],
        "format": "In-person"
    },

    {
        "url": "scRNA_2025/",
        "title": "Single Cell RNA-seq Analysis",
        "instructors": ["Tallulah Andrews", "Trevor Pugh", "Nicolas Ho", "Kevin Joannou", "Mobin Khoramjoo"],
        "tags": ["RNA-seq", "Analysis"],
        "regions": ["Ontario", "Alberta"],
        "year": 2025,
        "startDate": "2025-07-10",
        "endDate": "2025-07-11",
        "image": "img/legacy_icons/l-scRNA_icon.jpg",
        "locations": ["Ottawa, ON", "Edmonton, AB"],
        "format": "In-person"
    },

    {
        "url": "BMB_2025/",
        "title": "Beginner Microbiome Analysis",
        "instructors": ["Morgan Langille"],
        "tags": ["Microbiome"],
        "regions": ["BC"],
        "year": 2025,
        "startDate": "2025-05-26",
        "endDate": "2025-05-27",
        "image": "img/legacy_icons/l-BMB_icon.png",
        "locations": ["Vancouver, BC"],
        "format": "In-person"
    },

    {
        "url": "IDE_2024",
        "title": "Infectious Disease Genomic Epidemiology",
